# Generated by Django 6.0.2 on 2026-02-12 10:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_remove_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('quantity_purchased', models.IntegerField(help_text='Quantity bought from vendor')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price per unit at which product was purchased', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='purchase_invoices/')),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_added', to='dashboard_app.adminuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='dashboard_app.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='dashboard_app.vendor')),
            ],
            options={
                'verbose_name_plural': 'Purchase Entries',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
