# Generated by Django 6.0.2 on 2026-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_purchaseentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price for website/customers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit at which product was purchased from vendor', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: Quantity × Purchase Price', max_digits=10),
        ),
    ]
