# Generated by Django 6.0.2 on 2026-02-13 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_remove_product_stock_quantity_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hair_service', 'Hair Services'), ('beauty_service', 'Beauty & Skin Care Services'), ('makeup_service', 'Makeup Services'), ('spa_service', 'Spa & Massage Services'), ('nail_service', 'Nail Care Services'), ('bridal_service', 'Bridal Packages'), ('other', 'Other Services')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description for customers')),
                ('duration_minutes', models.IntegerField(help_text='Approximate duration in minutes')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price (can vary by employee expertise)', max_digits=10)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('display_on_website', models.BooleanField(default=True, help_text='Toggle to show/hide service on website')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('booking_type', models.CharField(choices=[('online', 'Online Booking'), ('offline', 'Offline (Walk-in)')], max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total calculated from all services', max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Advance amount paid during booking', max_digits=10)),
                ('special_notes', models.TextField(blank=True, help_text='Any special requests or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Receptionist who created this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to='dashboard_app.employee')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Price at time of booking (stored for record)', max_digits=10)),
                ('service_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('added_at_stage', models.CharField(choices=[('initial', 'Initial Booking'), ('additional', 'Additional Service')], default='initial', max_length=15)),
                ('is_additional', models.BooleanField(default=False, help_text='True if added after initial booking')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='dashboard_app.appointment')),
                ('employee', models.ForeignKey(help_text='Employee assigned to perform this service', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_services', to='dashboard_app.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='dashboard_app.service')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all services', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, help_text='GST amount (optional)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount after discount & GST', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Debit/Credit Card'), ('upi', 'UPI'), ('online', 'Online Payment')], default='cash', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='pending', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='dashboard_app.appointment')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_generated', to='dashboard_app.employee')),
            ],
            options={
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('employee_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('appointment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billed_services', to='dashboard_app.appointmentservice')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='dashboard_app.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='For birthday wishes & offers', null=True)),
                ('address_line', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline (Walk-in)'), ('both', 'Both')], default='offline', max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Receptionist who created this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to='dashboard_app.employee')),
            ],
            options={
                'ordering': ['-registered_on'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='dashboard_app.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dashboard_app.customer'),
        ),
        migrations.CreateModel(
            name='ServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('master', 'Master')], default='intermediate', max_length=20)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override base price for this employee (optional)', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Toggle if employee is currently offering this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='dashboard_app.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_employees', to='dashboard_app.service')),
            ],
            options={
                'ordering': ['-expertise_level', 'employee__full_name'],
                'unique_together': {('service', 'employee')},
            },
        ),
    ]
