# Generated by Django 6.0.2 on 2026-02-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_service_appointment_appointmentservice_bill_billitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service_notes',
            field=models.TextField(blank=True, help_text='Employee ke observations - kya kiya, kya discuss hua customer se', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to='dashboard_app.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_services', to='dashboard_app.employee'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to='dashboard_app.employee'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_on_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='quantity_purchased',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='display_on_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceemployee',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceemployee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ServiceProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('new', 'New Product Opened'), ('existing', 'Existing Product (Already Open)')], default='existing', help_text='New = stock deduct hoga | Existing = already open tha, stock nahi katega', max_length=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=1, help_text='Kitna use hua (e.g., 1 = 1 bottle, 0.5 = half bottle)', max_digits=6)),
                ('notes', models.CharField(blank=True, help_text="Extra note (e.g., 'Half bottle used', 'Applied twice')", max_length=300, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='dashboard_app.appointmentservice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='dashboard_app.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_usages_recorded', to='dashboard_app.employee')),
            ],
            options={
                'verbose_name': 'Service Product Usage',
                'verbose_name_plural': 'Service Product Usages',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
